// components/article-section.tsx
import React from 'react'
import { ArticleTypedef } from '@/lib/typedef/article-typedef'
import Image from 'next/image'

interface ArticleSectionProps {
  section: ArticleTypedef
  index: number
  totalSections: number
}

/**
 * ArticleSection renders a section with a header, image, and paragraphs.
 * Supports different formats of paragraphs including arrays, objects, and strings.
 * Implements lazy loading and proper image sizing for improved performance.
 */
export function ArticleSection({
  section,
  index,
  totalSections,
}: ArticleSectionProps): React.ReactElement {
  const renderParagraphs = () => {
    const paragraphs = section.paragraphs

    if (Array.isArray(paragraphs)) {
      return paragraphs.map((paragraph, pIndex) => (
        <p key={`paragraph-${pIndex}`} className="mb-3 sm:mb-4">
          {paragraph}
        </p>
      ))
    }

    if (typeof paragraphs === 'object' && paragraphs !== null) {
      return Object.entries(paragraphs).map(([key, value]) => (
        <p key={key} className="mb-3 sm:mb-4">
          {String(value)}
        </p>
      ))
    }

    if (typeof paragraphs === 'string') {
      return <p className="mb-3 sm:mb-4">{paragraphs}</p>
    }

    return null
  }

  const isFirstSection = index === 0
  const isLastSection = index === totalSections - 1

  return (
    <section aria-labelledby={`section-header-${index}`}>
      <div className="p-6 sm:p-8">
        <h2
          id={`section-header-${index}`}
          className="mb-4 text-2xl font-bold text-gray-900 dark:text-white sm:text-3xl lg:text-4xl"
        >
          {section.header}
        </h2>
        <div className="mb-6 sm:mb-8">
          <Image
            src={section.image}
            alt={`Illustration for ${section.header}`}
            width={1000}
            height={500}
            className="h-auto w-full rounded-lg object-cover shadow-sm"
            priority={isFirstSection}
            loading={isFirstSection ? 'eager' : 'lazy'}
            quality={75}
            sizes="(max-width: 640px) 100vw, (max-width: 1024px) 75vw, 50vw"
            placeholder="blur"
            blurDataURL="/placeholder.svg"
          />
        </div>
        <div className="prose prose-sm sm:prose-base lg:prose-lg dark:prose-invert max-w-none">
          {renderParagraphs()}
        </div>
      </div>
    </section>
  )
}

// src/components/ArticleSection.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import type { ArticleTypedef } from '@/lib/typedef/article-typedef'

interface ArticleSectionProps {
  section: ArticleTypedef
  index: number
  totalSections: number
}

const props = defineProps<ArticleSectionProps>()

const imageError = ref(false)
const imageLoaded = ref(false)

const imageAlt = computed(() => `Illustration for ${props.section.header}`)

const isObject = (value: unknown): value is Record<string, unknown> => {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

const renderableParagraphs = computed(() => {
  const paragraphs = props.section.paragraphs

  if (Array.isArray(paragraphs)) {
    return paragraphs.filter(p => p && typeof p === 'string' && p.trim())
  }

  if (isObject(paragraphs)) {
    return Object.values(paragraphs)
      .map(String)
      .filter(p => p && p.trim())
  }

  if (typeof paragraphs === 'string' && paragraphs) {
    return [paragraphs]
  }

  return []
})

const hasContent = computed(() => renderableParagraphs.value.length > 0)

const handleImageError = () => {
  imageError.value = true
  console.warn(`Failed to load image: ${props.section.image}`)
}

const handleImageLoad = () => {
  imageLoaded.value = true
}
</script>

<template>
  <section :aria-labelledby="`section-header-${index}`" class="scroll-mt-16">
    <div class="p-6 sm:p-8">
      <header>
        <h2
          :id="`section-header-${index}`"
          class="mb-4 text-2xl font-bold text-gray-900 sm:text-3xl lg:text-4xl dark:text-white"
        >
          {{ section.header }}
        </h2>
      </header>

      <figure class="mb-6 sm:mb-8">
        <img
          :src="section.image"
          :alt="imageAlt"
          class="h-auto w-full rounded-lg object-cover shadow-sm transition-opacity duration-300"
          loading="eager"
          @error="handleImageError"
          @load="handleImageLoad"
        />
        <figcaption class="sr-only">
          {{ imageAlt }}
        </figcaption>
      </figure>

      <div
        class="prose prose-sm sm:prose-base lg:prose-lg dark:prose-invert max-w-none"
        role="region"
        :aria-label="`Content for ${section.header}`"
      >
        <template v-if="hasContent">
          <p
            v-for="(paragraph, pIndex) in renderableParagraphs"
            :key="`paragraph-${pIndex}`"
            class="mb-3 sm:mb-4"
          >
            {{ paragraph }}
          </p>
        </template>
        <p v-else class="text-gray-500 italic">
          No content available for this section.
        </p>
      </div>
    </div>
  </section>
</template>

<style scoped>
/* Add any component-specific styles if needed */
</style>
